!!de.christianbernstein.bernie.modules.net.NetModuleConfigShard
ssl: false
sslCertificateDir: '{root_dir}/ssl/'
sslCertificateFactory: X.509
sslContext: TLS
sslKeyFactory: RSA
sslKeyManagerFactory: SunX509
sslKeyStore: JKS
sslPrivateKeyFile: {location: privkey.pem, type: FS_RELATIVE}
sslProviderType: letsencrypt
sslRelativeCertificatePath: cert.pem
sslRelativePrivateKeyPath: privkey.pem
syncClose: true
syncOpen: true
